---
title: "Resume"
output: html_document
---



## Academic Experience

##### Columbia University – Mailman School of Public Health
September 2021 - May 2023<br>
New York, NY<br>
Master of Science in Biostatistics


##### The Pennsylvania State University
August 2017 - December 2020<br>
University Park, PA<br>
Bachelor of Science in Mathematics and Finance




## Work Experience

##### ICAP at Columbia University
November 2021 – Present<br>
New York, NY<br>
Program Assistant<br>
* Provide administrative support for ICAP’s award, proposal, project, knowledge management system, budgeting, and financial performance tracking system<br>
* Schedule meetings and logistics for testing, training, and other consultation/feedback sessions for ICAP staff in New York and country offices<br>
* Assist with data cleaning, entry, document migration, activity template set-up, and basic troubleshooting support<br>
* Assist with editing user guidance documentation, user set-up, initial orientation, FAQ resources and support for training/capacity building efforts


##### Surge Business Development
September 2019 – May 2020<br>
State College, PA<br>
Consultant Intern<br>
* Utilized SWOT analysis for 4 clients to research competitors and industry to attract more customers and increase revenue<br>
* Wrote 30-page analysis report which provided suggestions on clients’ products and services such as sales package options, advertising, and social media strategy<br>
* Designed websites using WordPress, optimized online search results, and built marketing plans for 6 start-up companies around the country




## Leadership Experience

##### Humana-Mays Healthcare Analytics Case Competition
September 2021 – October 2021<br>
National<br>
Team Leader<br>
* Led a team of 4 to build and implement quantitative evaluation models, using linear regression on 500,000 + survey-sampled data points to estimate U.S. residents’ Covid-19 vaccine hesitancy<br>
* Developed code in R tidyverse and dplyr packages to input data, clean the dataset, analyze categorical & quantitative features of the sampled U.S. residents, and predict the association between each feature and Covid- 19 vaccine status<br>
* Communicated findings and translated technical results, including visualization and written reports, to surface implications and recommendations to address Covid-19 vaccine hesitancy


##### Penn State Robo X Club
April 2019 – June 2020<br>
State College, PA<br>
Vice-President<br>
* Developed a collaboration with 10 other student organizations at Penn State<br>
* Recruited 40 students for technical groups and 20 students for non-technical groups<br>
* Managed $10,000 budget for the student organization<br>
* Represented Penn State in RoboMaster Robotics Competition and won 6th place in international district




