---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(dplyr)
library(tidyr)
library(plotly)
library(ggridges)
library(httr)
library(jsonlite)
library(flexdashboard)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data("instacart")

instacart_1 =
  count(instacart, department) %>% 
  arrange(n) %>% 
  mutate(
    department = factor(department, levels = department)
  )

instacart_1 %>% 
  plot_ly(x = ~n, y = ~department, color = ~department, type = "bar", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

instacart_2 = instacart %>% 
  filter( department == "dairy eggs") %>%
  mutate(department = str_to_title(department)) %>% 
  mutate(
    department = fct_infreq(department),
    department = fct_recode(department)) 
 # group_by(aisle, days_since_prior_orde) %>% 
 #  summarize(n_obs = n())

 # select(department, order_number, days_since_prior_order)

instacart_2 %>% 
  plot_ly(x = ~aisle, y = ~days_since_prior_order, color = ~department, alpha = .5,
    type = "scatter", mode = "markers"
  )
```

### Chart C

```{r}
data("instacart")

instacart_3 = instacart %>% 
  filter(department != Missing) %>% 
  mutate(department = str_to_title(department)) %>% 
  mutate(
    department = fct_infreq(department),
    department = fct_recode(department)) 
  

instacart_3 %>% 
  plot_ly(
      x = ~department, y = ~days_since_prior_order, color = ~department,
      type = "box", colors = "viridis"
    ) 
```

```{r}
# instacart_4 =
#   count(instacart, aisle) %>% 
#   arrange(n) %>% 
#   mutate(
#     department = factor(department, levels = department)
#   )
```


