---
title: "Plotly"
output: html_document
---

# Examples of Plotly

## Bar plot
 
Install `Instacart` Data.
```{r}
library(tidyverse)
library(p8105.datasets)
library(dplyr)
library(tidyr)
library(plotly)
data("instacart")
```

Plot that shows the number of items ordered in each department.
```{r}
instacart_department =
  count(instacart, department) %>% 
  arrange(n) %>% 
  mutate(
    department = factor(department, levels = department)
  )


instacart_department %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")
```


## Scatterplot
```{r}
library(ggridges)
```

Install `NOAA` data.
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Create a scatterplot
```{r}
weather_df %>% 
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~name, alpha = .5,
    type = "scatter", mode = "markers"
  )
```

## Box plot
```{r}
library(httr)
library(jsonlite)
```

Import `NYC Restaurant Inspections` data.
```{r}
data("rest_inspec")
```

Plot that shows score of restaurants at each area in New York city.
```{r}
rest_inspec %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro)) %>% 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) %>%
  mutate(
    boro = fct_infreq(boro),
    boro = fct_recode(boro)) %>% 
  plot_ly(
    x = ~boro, y = ~score, color = ~boro, 
    type = "box", colors = "viridis"
  )
```









